### ISSUE TITLE
http://localhost:1086/无法访问

### ISSUE THREAD

**Issue by bnuchengg** [kccd/nkc#498]
安装完成后通过哪个端口访问网站?
谢谢

**Comment by pengxiguaa** [comment]
> 安装完成后通过哪个端口访问网站?
> 谢谢

第一次在项目根目录下执行`node server.js`将进入安装流程，安装完依赖后可通过浏览器访问`http://localhost:9000`填写管理员账号密码、网站端口以及数据库信息。安装完成后，重新执行`node server.js`，在浏览器输入`http://localhost:9000`（默认9000）即可访问网站。
